(()=>{const C=window.CHILLOUT_CONFIG||{},demo=C.DEMO_MODE===true||!C.SUPABASE_URL||C.SUPABASE_URL.includes("YOUR-PROJECT"),db=!demo&&window.supabase?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null,$=id=>document.getElementById(id),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),today=()=>new Date().toISOString().slice(0,10);let settings=JSON.parse(localStorage.getItem('co_settings')||'{"name":"Chill Out","phone":"Sagar @ 9886025749","review":"","logo":"","qrOrderingEnabled":true}'),phoneNumbers=JSON.parse(localStorage.getItem('co_phone_numbers')||'null')||[{id:1,label:'Sagar',phone:'9886025749',enabled:true}],menu=JSON.parse(localStorage.getItem('co_menu')||'null')||[{id:1,name:'Classic Waffle',cat:'Waffles',desc:'Fresh golden waffle.',price:99,icon:'🧇',active:true},{id:2,name:'Chocolate Thick Shake',cat:'Thick Shakes',desc:'Rich creamy chocolate shake.',price:129,icon:'🥤',active:true},{id:3,name:'Fresh Fruit Juice',cat:'Fruit Juices',desc:'Fresh seasonal fruit.',price:89,icon:'🍹',active:true},{id:4,name:'Ice Cream Scoop',cat:'Ice Creams',desc:'Cool creamy favourite.',price:79,icon:'🍦',active:true},{id:5,name:'Tea / Coffee',cat:'Tea & Coffee',desc:'Warm cup for every mood.',price:49,icon:'☕',active:true},{id:6,name:'Cafe Snacks',cat:'Snacks',desc:'Quick bites to chill with.',price:69,icon:'🍟',active:true}],offers=JSON.parse(localStorage.getItem('co_offers')||'null')||[{id:1,title:'Chill Combo',cat:'COMBO',desc:'Waffle + Thick Shake.',active:true},{id:2,title:'Fresh Sip',cat:'FRESH',desc:'Choose a fresh fruit juice.',active:true}],cart=JSON.parse(localStorage.getItem('co_cart')||'[]'),filter='All',role=null,user=null;const qr=new URLSearchParams(location.search).get('table')||'';
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2800)}function save(){localStorage.setItem('co_settings',JSON.stringify(settings));localStorage.setItem('co_menu',JSON.stringify(menu));localStorage.setItem('co_offers',JSON.stringify(offers));localStorage.setItem('co_phone_numbers',JSON.stringify(phoneNumbers));localStorage.setItem('co_cart',JSON.stringify(cart))}function show(id){$(id).showModal()}function hide(id){if($(id).open)$(id).close()}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));$('year').textContent=new Date().getFullYear();
function normalizeSettings(){
  settings=settings||{};
  if(!Array.isArray(settings.phones)){
    const raw=String(settings.phone||'').trim();
    settings.phones=raw? [{label:'Call to Order',number:raw.replace(/^[^0-9+]*@\s*/,'').trim()||raw,active:true}] : [];
  }
  if(typeof settings.qrEnabled!=='boolean') settings.qrEnabled=true;
  if(!settings.review) settings.review='https://share.google/RRQAxP3qKVVN0pDLg';
}
function phoneBookText(){return settings.phones.filter(x=>x&&x.number).map(x=>`${x.label||'Call to Order'}: ${x.number}`).join(' | ')}
function phoneMeta(){return '__CO_PHONEBOOK__'+JSON.stringify(settings.phones)}
function reviewMeta(){return '__CO_META__'+JSON.stringify({review:settings.review||'',qrEnabled:!!settings.qrEnabled})}
function parseDbSettings(row){
  let phones=[], phone=String(row.phone||'');
  if(phone.startsWith('__CO_PHONEBOOK__')){try{phones=JSON.parse(phone.slice('__CO_PHONEBOOK__'.length))}catch{phones=[]}}
  if(!phones.length && phone) phones=[{label:'Call to Order',number:phone.replace(/^[^0-9+]*@\s*/,'').trim()||phone,active:true}];
  let review=row.google_review_url||'', qrEnabled=true;
  if(review.startsWith('__CO_META__')){try{const m=JSON.parse(review.slice('__CO_META__'.length));review=m.review||'';qrEnabled=m.qrEnabled!==false}catch{}}
  return {name:row.cafe_name||'Chill Out',phone:phones.map(x=>`${x.label||'Call to Order'}: ${x.number||''}`).join(' | '),phones,review:review||'https://share.google/RRQAxP3qKVVN0pDLg',qrEnabled,logo:row.logo_url||''};
}
function pub(){
  normalizeSettings();
  $('phone').innerHTML=settings.phones.filter(x=>x.active&&x.number).map(x=>`<a class="callBtn" href="tel:${esc(String(x.number).replace(/[^0-9+]/g,''))}">☎ ${esc(x.label||'Call to Order')}: ${esc(x.number)}</a>`).join('')||'<span>No phone ordering number set.</span>';
  $('cafeName').firstChild.textContent=(settings.name||'Chill Out').toUpperCase();
  $('reviewLink').href=settings.review||'#';
  if(settings.logo)$('logo').src=settings.logo;
  $('table').value=qr||$('table').value||'';
  $('tableHint').textContent=qr?'QR table detected: '+qr:'';
  const orderNote=$('orderingState');
  if(orderNote) orderNote.textContent=settings.qrEnabled?'🟢 Online / QR ordering is available.':'🔴 Online ordering is currently unavailable. Please order at the counter.';
  let cats=['All',...new Set(menu.filter(x=>x.active).map(x=>x.cat))];
  $('filters').innerHTML=cats.map(c=>`<button class="filter ${c==filter?'active':''}" data-c="${esc(c)}">${esc(c)}</button>`).join('');
  document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{filter=b.dataset.c;pub()});
  let ms=menu.filter(x=>x.active&&(filter==='All'||x.cat===filter));
  $('menuGrid').innerHTML=ms.map(x=>`<article class="card"><div class="icon">${x.icon||'🍽️'}</div><h3>${esc(x.name)}</h3><p>${esc(x.desc||'')}</p><div class="cardBottom"><span class="price">${money(x.price)}</span><button class="add" data-add="${x.id}" ${settings.qrEnabled?'':'disabled'}>${settings.qrEnabled?'Add':'Ordering off'}</button></div></article>`).join('');
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));
  $('offerGrid').innerHTML=offers.filter(x=>x.active).map(x=>`<article class="offer"><span>${esc(x.cat||'SPECIAL')}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p></article>`).join('');
  renderCart();refreshPoints();
}

function add(id){if(settings.qrOrderingEnabled===false)return toast('Online ordering is currently unavailable. Please order at the counter.');let m=menu.find(x=>x.id===id),q=cart.find(x=>x.id===id);q?q.qty++:cart.push({id,name:m.name,price:+m.price,qty:1});save();renderCart();toast(m.name+' added')};function change(id,d){let q=cart.find(x=>x.id===id);if(!q)return;q.qty+=d;if(q.qty<1)cart=cart.filter(x=>x.id!==id);save();renderCart()};function renderCart(){ $('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartLine"><span><b>${esc(x.name)}</b><br><small>${money(x.price)}</small></span><div class="qty"><button data-d="${x.id}">−</button>${x.qty}<button data-i="${x.id}">+</button></div><b>${money(x.price*x.qty)}</b></div>`).join(''):'<p>No items yet.</p>';document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>change(+b.dataset.d,-1));document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>change(+b.dataset.i,1));$('total').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0))}
$('cartBtn').onclick=$('heroCart').onclick=()=>{renderCart();show('cartModal')};$('customerBtn').onclick=$('loyaltyBtn').onclick=()=>show('customerModal');$('skip').onclick=()=>{hide('customerModal');toast('Guest mode enabled')};$('staffBtn').onclick=()=>show('staffModal');
async function login(email,pw){if(demo){if(!email||!pw)throw Error('Enter demo email and password');return{id:'demo',email,role:email.toLowerCase().startsWith('owner')?'owner':'worker'}}let r=await db.auth.signInWithPassword({email,password:pw});if(r.error){if(email.trim().toLowerCase()==='editorgaadu@gmail.com'){let s=await db.auth.signUp({email,password:pw});if(s.error)throw r.error;r=await db.auth.signInWithPassword({email,password:pw})}else throw r.error}if(r.error)throw r.error;let p=await db.from('profiles').select('role,full_name').eq('id',r.data.user.id).single();if(p.error)throw p.error;if(p.data.role==='customer'&&email.trim().toLowerCase()==='editorgaadu@gmail.com'){let b=await db.functions.invoke('manage-staff-v2',{body:{action:'bootstrap-primary'}});if(!b.error){p.data.role='owner';p.data.full_name='Primary Owner'}}return{...r.data.user,role:p.data.role,name:p.data.full_name}}
$('staffForm').onsubmit=async e=>{e.preventDefault();try{user=await login($('staffEmail').value,$('staffPass').value);role=user.role;hide('staffModal');role==='owner'?owner():role==='worker'?worker():toast('Staff role required')}catch(x){toast(x.message)}};$('customerForm').onsubmit=async e=>{e.preventDefault();let email=$('custEmail').value,pw=$('custPass').value;if(!email||!pw)return toast('Enter email/password or Skip');try{if(demo){user={id:'demo-customer',email,role:'customer'}}else{let r=await db.auth.signInWithPassword({email,password:pw});if(r.error)r=await db.auth.signUp({email,password:pw});if(r.error)throw r.error;user={id:r.data.user.id,email,role:'customer'}}hide('customerModal');await refreshPoints();toast('Customer account ready')}catch(x){toast(x.message)}};
async function place(){if(settings.qrOrderingEnabled===false)return toast('Online ordering is currently unavailable. Please order at the counter.');if(!cart.length)return toast('Cart is empty');let items=cart.map(x=>`${x.name} x${x.qty}`).join(', '),total=cart.reduce((a,x)=>a+x.price*x.qty,0),label=$('orderName').value.trim()||'Guest',table=$('table').value.trim(),note=$('note').value.trim(),row={customer_label:label+(table?' • Table '+table:''),items:items+(note?' • Note: '+note:''),total,status:'noted',created_at:new Date().toISOString(),customer_user_id:user?.role==='customer'?user.id:null};try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]');a.push({id:Date.now(),...row});localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').insert(row);if(r.error)throw r.error}cart=[];save();renderCart();hide('cartModal');toast('Order sent to cafe — '+money(total))}catch(x){toast(x.message)}}$('place').onclick=place;
async function refreshPoints(){let p=Number(localStorage.getItem('co_points')||0);if(!demo&&user?.role==='customer'){let r=await db.from('loyalty_accounts').select('points').eq('user_id',user.id).maybeSingle();p=r.data?.points||0}$('points').textContent=p;$('loyaltyUser').textContent=user?.email?user.email.toUpperCase():'CUSTOMER REWARDS'}
async function staffCheck(wanted){if(demo)return true;let s=await db.auth.getUser();if(!s.data.user)throw Error('Please sign in');let p=await db.from('profiles').select('role').eq('id',s.data.user.id).single();if(p.error||p.data.role!==wanted)throw Error('Access denied')}
function tabs(){document.querySelectorAll('#ownerTabs button').forEach(b=>b.onclick=()=>loadOwnerTab(b.dataset.tab))}async function owner(){try{await staffCheck('owner');show('ownerModal');tabs();loadOwnerTab('overview')}catch(x){toast(x.message)}}async function loadOwnerTab(t){document.querySelectorAll('#ownerTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));let c=$('ownerContent');if(t==='overview')return overview(c);if(t==='menu')return menuAdmin(c);if(t==='offers')return offersAdmin(c);if(t==='orders')return ordersAdmin(c);if(t==='sales')return salesAdmin(c);if(t==='loyaltyAdmin')return loyaltyAdmin(c);if(t==='settings')return settingsAdmin(c);if(t==='phones')return phoneAdmin(c);if(t==='staff')return staffAdmin(c)}
async function getOrders(){if(demo)return JSON.parse(localStorage.getItem('co_orders')||'[]').sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));let r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(300);if(r.error)throw r.error;return r.data||[]}function orderRow(o){return `<div class="orderRow"><span><b>${esc(o.customer_label)}</b><br><small>${esc(o.items)}</small><br><small>${new Date(o.created_at).toLocaleString()}</small></span><span>${money(o.total)}<br><select data-status="${o.id}"><option ${o.status==='noted'?'selected':''}>noted</option><option ${o.status==='preparing'?'selected':''}>preparing</option><option ${o.status==='ready'?'selected':''}>ready</option><option ${o.status==='served'?'selected':''}>served</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select></span></div>`}async function bindStatuses(c,refresh){c.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]'),o=a.find(x=>String(x.id)===s.dataset.status);if(o)o.status=s.value;localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').update({status:s.value}).eq('id',s.dataset.status);if(r.error)throw r.error}toast('Status updated');refresh()}catch(x){toast(x.message)}})}
async function overview(c){let o=await getOrders(),d=o.filter(x=>x.created_at.slice(0,10)===today()&&x.status!=='cancelled'),rev=d.reduce((a,x)=>a+Number(x.total),0),open=o.filter(x=>['noted','preparing','ready'].includes(x.status)).length;c.innerHTML=`<div class="kpis"><div class="kpi"><span>ORDERS TODAY</span><b>${d.length}</b></div><div class="kpi"><span>REVENUE TODAY</span><b>${money(rev)}</b></div><div class="kpi"><span>OPEN ORDERS</span><b>${open}</b></div><div class="kpi"><span>MENU ITEMS</span><b>${menu.length}</b></div><div class="kpi"><span>MODE</span><b>${demo?'DEMO':'LIVE'}</b></div></div><div class="panel"><h3>Recent orders</h3>${d.slice(0,8).map(orderRow).join('')||'No orders today.'}</div>`}
function menuAdmin(c){c.innerHTML=`<div class="panel"><div class="row"><h3>Menu Management</h3><button class="solid" id="newMenu">Add Item</button></div><div>${menu.map(x=>`<div class="adminRow"><span><b>${esc(x.name)}</b><br><small>${esc(x.cat)} · ${money(x.price)} · ${x.active?'Available':'Hidden'}</small></span><span class="actions"><button class="small" data-editm="${x.id}">Edit</button><button class="small danger" data-delm="${x.id}">Delete</button></span></div>`).join('')}</div></div>`;$('newMenu').onclick=()=>edit('menu');c.querySelectorAll('[data-editm]').forEach(b=>b.onclick=()=>edit('menu',+b.dataset.editm));c.querySelectorAll('[data-delm]').forEach(b=>b.onclick=()=>del('menu',+b.dataset.delm))}function offersAdmin(c){c.innerHTML=`<div class="panel"><div class="row"><h3>Offers Management</h3><button class="solid" id="newOffer">Add Offer</button></div>${offers.map(x=>`<div class="adminRow"><span><b>${esc(x.title)}</b><br><small>${esc(x.cat)} · ${x.active?'Active':'Hidden'}</small></span><span class="actions"><button class="small" data-edito="${x.id}">Edit</button><button class="small danger" data-delo="${x.id}">Delete</button></span></div>`).join('')}</div>`;$('newOffer').onclick=()=>edit('offer');c.querySelectorAll('[data-edito]').forEach(b=>b.onclick=()=>edit('offer',+b.dataset.edito));c.querySelectorAll('[data-delo]').forEach(b=>b.onclick=()=>del('offer',+b.dataset.delo))}async function ordersAdmin(c){let o=await getOrders();c.innerHTML=`<div class="panel"><div class="row"><h3>All Orders</h3><button class="outline" id="ro">Refresh</button></div><div id="olist">${o.map(orderRow).join('')||'No orders.'}</div></div>`;await bindStatuses($('olist'),()=>ordersAdmin(c));$('ro').onclick=()=>ordersAdmin(c)}
async function salesAdmin(c){let o=await getOrders();let from=today(),to=today();c.innerHTML=`<div class="panel"><h3>Sales Report</h3><input id="from" type="date" value="${from}"><input id="to" type="date" value="${to}"><button class="solid" id="runSales">Run Report</button><div id="report"></div></div>`;$('runSales').onclick=async()=>{let f=$('from').value,t=$('to').value,r=(await getOrders()).filter(x=>x.created_at.slice(0,10)>=f&&x.created_at.slice(0,10)<=t&&x.status!=='cancelled'),v=r.reduce((a,x)=>a+Number(x.total),0);$('report').innerHTML=`<div class="reportCards"><div class="reportCard"><span>ORDERS</span><b>${r.length}</b></div><div class="reportCard"><span>REVENUE</span><b>${money(v)}</b></div><div class="reportCard"><span>AVG ORDER</span><b>${money(r.length?v/r.length:0)}</b></div><div class="reportCard"><span>PERIOD</span><b>${f} → ${t}</b></div></div><table><tr><th>Date</th><th>Items</th><th>Total</th></tr>${r.map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString()}</td><td>${esc(x.items)}</td><td>${money(x.total)}</td></tr>`).join('')}</table>`};$('runSales').click()}
function loyaltyAdmin(c){let l=JSON.parse(localStorage.getItem('co_loyalty')||'{"per100":10,"rewardPoints":100,"rewardValue":50}');c.innerHTML=`<div class="panel"><h3>Loyalty Rules</h3><label>Points per ₹100<input id="lp" type="number" value="${l.per100}"></label><label>Reward points<input id="lrp" type="number" value="${l.rewardPoints}"></label><label>Reward value ₹<input id="lrv" type="number" value="${l.rewardValue}"></label><button class="solid" id="saveL">Save</button></div>`;$('saveL').onclick=async()=>{l={per100:+$('lp').value,rewardPoints:+$('lrp').value,rewardValue:+$('lrv').value};localStorage.setItem('co_loyalty',JSON.stringify(l));if(!demo){let r=await db.from('loyalty_settings').upsert({id:1,points_per_100:l.per100,reward_points:l.rewardPoints,reward_value:l.rewardValue});if(r.error)return toast(r.error.message)}toast('Loyalty rules saved')}}function settingsAdmin(c){
  normalizeSettings();
  const rows=settings.phones.map((p,i)=>`<div class="adminRow phoneRow"><span><b>${esc(p.label||'Call to Order')}</b><br><small>${esc(p.number||'')} · ${p.active?'Active':'Disabled'}</small></span><span class="actions"><button class="small" data-phone-edit="${i}">Edit</button><button class="small danger" data-phone-del="${i}">Delete</button></span></div>`).join('');
  c.innerHTML=`<div class="panel"><h3>Public Settings</h3><input id="sn" value="${esc(settings.name)}" placeholder="Cafe name"><input id="sr" value="${esc(settings.review)}" placeholder="Google review URL"><input id="sl" value="${esc(settings.logo)}" placeholder="Logo URL (optional)">
  <label class="toggle"><input id="qrEnabled" type="checkbox" ${settings.qrEnabled?'checked':''}> <b>QR / Online Ordering ON</b></label>
  <p class="security">When OFF, customers can still see the menu and phone numbers, but cannot place QR/online orders.</p>
  <h3>Call to Order Numbers</h3><div id="phoneList">${rows||'<p>No numbers yet.</p>'}</div><button class="outline" id="addPhone">+ Add Phone Number</button>
  <div class="ownerBox"><b>Primary Owner</b><br>${esc('Editorgaadu@gmail.com')}<p>Primary Owner cannot be removed. Additional owners use the same Owner Dashboard permissions; account promotion is controlled through Supabase Auth/RLS.</p></div>
  <button class="solid" id="saveS">Save Settings</button><p class="security"><b>Security:</b> only the owner role may update settings in production.</p></div>`;
  function editPhone(i){const p=settings.phones[i]||{label:'Call to Order',number:'',active:true};const label=prompt('Phone label',p.label||'Call to Order');if(label===null)return;const number=prompt('Phone number',p.number||'');if(number===null)return;const active=confirm('Keep this number active?');settings.phones[i]={label:label.trim()||'Call to Order',number:number.trim(),active};renderRows();}
  function renderRows(){const box=$('phoneList');box.innerHTML=settings.phones.map((p,i)=>`<div class="adminRow phoneRow"><span><b>${esc(p.label||'Call to Order')}</b><br><small>${esc(p.number||'')} · ${p.active?'Active':'Disabled'}</small></span><span class="actions"><button class="small" data-phone-edit="${i}">Edit</button><button class="small danger" data-phone-del="${i}">Delete</button></span></div>`).join('')||'<p>No numbers yet.</p>';box.querySelectorAll('[data-phone-edit]').forEach(b=>b.onclick=()=>editPhone(+b.dataset.phoneEdit));box.querySelectorAll('[data-phone-del]').forEach(b=>b.onclick=()=>{settings.phones.splice(+b.dataset.phoneDel,1);renderRows()});}
  renderRows();$('addPhone').onclick=()=>{settings.phones.push({label:'Call to Order',number:'',active:true});editPhone(settings.phones.length-1)};
  $('saveS').onclick=async()=>{let n={...settings,name:$('sn').value.trim()||'Chill Out',review:$('sr').value.trim()||'https://share.google/RRQAxP3qKVVN0pDLg',logo:$('sl').value.trim(),qrEnabled:$('qrEnabled').checked};settings=n;if(demo){save()}else{let r=await db.from('site_settings').upsert({id:1,cafe_name:n.name,phone:phoneMeta(),google_review_url:reviewMeta(),logo_url:n.logo});if(r.error)return toast(r.error.message);save()}pub();toast('Settings saved')};
}
function edit(type,id){let o=type==='menu'?menu.find(x=>x.id===id):offers.find(x=>x.id===id);$('editId').value=id||'';$('editType').value=type;$('editTitle').textContent=(id?'Edit ':'Add ')+(type==='menu'?'Menu Item':'Offer');$('editName').value=o?.name||o?.title||'';$('editCat').value=o?.cat||'';$('editDesc').value=o?.desc||'';$('editPrice').value=o?.price??'';$('editPrice').style.display=type==='menu'?'block':'none';$('editActive').checked=o?.active??true;show('editModal')}async function del(type,id){if(!confirm('Delete this item?'))return;if(demo){if(type==='menu')menu=menu.filter(x=>x.id!==id);else offers=offers.filter(x=>x.id!==id);save();pub();loadOwnerTab(type==='menu'?'menu':'offers');return}let table=type==='menu'?'menu_items':'offers',r=await db.from(table).delete().eq('id',id);if(r.error)return toast(r.error.message);loadOwnerTab(type==='menu'?'menu':'offers')}
$('editForm').onsubmit=async e=>{e.preventDefault();let type=$('editType').value,id=+$('editId').value||null;try{if(demo){if(type==='menu'){let o={id:id||Date.now(),name:$('editName').value,cat:$('editCat').value||'Other',desc:$('editDesc').value,price:+$('editPrice').value,active:$('editActive').checked,icon:'🍽️'};id?Object.assign(menu.find(x=>x.id===id),o):menu.push(o)}else{let o={id:id||Date.now(),title:$('editName').value,cat:$('editCat').value||'SPECIAL',desc:$('editDesc').value,active:$('editActive').checked};id?Object.assign(offers.find(x=>x.id===id),o):offers.push(o)}save()}else{let table=type==='menu'?'menu_items':'offers',p=type==='menu'?{name:$('editName').value,category:$('editCat').value||'Other',description:$('editDesc').value,price:+$('editPrice').value,is_available:$('editActive').checked}:{title:$('editName').value,category:$('editCat').value||'SPECIAL',description:$('editDesc').value,is_active:$('editActive').checked};let r=id?await db.from(table).update(p).eq('id',id):await db.from(table).insert(p);if(r.error)throw r.error}hide('editModal');pub();toast('Saved');loadOwnerTab(type==='menu'?'menu':'offers')}catch(x){toast(x.message)}};
async function worker(){try{await staffCheck('worker');show('workerModal');loadWorker()}catch(x){toast(x.message)}}async function loadWorker(){let o=await getOrders();$('workerOrders').innerHTML=o.map(orderRow).join('')||'No orders.';await bindStatuses($('workerOrders'),loadWorker)}$('workerForm').onsubmit=async e=>{e.preventDefault();let row={customer_label:$('wCustomer').value,items:$('wItems').value,total:+$('wTotal').value,status:'noted',created_at:new Date().toISOString()};try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]');a.push({id:Date.now(),...row});localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').insert({...row,created_by:user.id});if(r.error)throw r.error}e.target.reset();toast('Order saved');loadWorker()}catch(x){toast(x.message)}};$('refreshWorker').onclick=loadWorker;
$('ownerLogout').onclick=async()=>{if(db)await db.auth.signOut();hide('ownerModal');role=null};$('workerLogout').onclick=async()=>{if(db)await db.auth.signOut();hide('workerModal');role=null};pub();if(!demo)(async()=>{try{let s=await db.from('site_settings').select('*').eq('id',1).maybeSingle();if(s.data)settings={name:s.data.cafe_name,phone:s.data.phone,review:s.data.google_review_url,logo:s.data.logo_url,qrOrderingEnabled:s.data.qr_ordering_enabled!==false};let pn=await db.from('phone_numbers').select('*').eq('enabled',true).order('id');if(pn.data)phoneNumbers=pn.data;let m=await db.from('menu_items').select('*').eq('is_available',true).order('name');if(m.data)menu=m.data.map(x=>({id:x.id,name:x.name,cat:x.category,desc:x.description,price:x.price,active:true,icon:x.icon||'🍽️'}));let o=await db.from('offers').select('*').eq('is_active',true);if(o.data)offers=o.data.map(x=>({id:x.id,title:x.title,cat:x.category,desc:x.description,active:true}));pub()}catch(e){console.warn(e)}})()})();
