(()=>{const C=window.CHILLOUT_CONFIG||{},demo=C.DEMO_MODE===true||!C.SUPABASE_URL||C.SUPABASE_URL.includes("YOUR-PROJECT"),db=!demo&&window.supabase?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null,$=id=>document.getElementById(id),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),today=()=>new Date().toISOString().slice(0,10);let settings=JSON.parse(localStorage.getItem('co_settings')||'{"name":"Chill Out","phone":"Sagar @ 9886025749","review":"","logo":"","qrOrderingEnabled":true}'),phoneNumbers=JSON.parse(localStorage.getItem('co_phone_numbers')||'null')||[{id:1,label:'Sagar',phone:'9886025749',enabled:true}],menu=JSON.parse(localStorage.getItem('co_menu')||'null')||[{id:1,name:'Classic Waffle',cat:'Waffles',desc:'Fresh golden waffle.',price:99,icon:'🧇',active:true},{id:2,name:'Chocolate Thick Shake',cat:'Thick Shakes',desc:'Rich creamy chocolate shake.',price:129,icon:'🥤',active:true},{id:3,name:'Fresh Fruit Juice',cat:'Fruit Juices',desc:'Fresh seasonal fruit.',price:89,icon:'🍹',active:true},{id:4,name:'Ice Cream Scoop',cat:'Ice Creams',desc:'Cool creamy favourite.',price:79,icon:'🍦',active:true},{id:5,name:'Tea / Coffee',cat:'Tea & Coffee',desc:'Warm cup for every mood.',price:49,icon:'☕',active:true},{id:6,name:'Cafe Snacks',cat:'Snacks',desc:'Quick bites to chill with.',price:69,icon:'🍟',active:true}],offers=JSON.parse(localStorage.getItem('co_offers')||'null')||[{id:1,title:'Chill Combo',cat:'COMBO',desc:'Waffle + Thick Shake.',active:true},{id:2,title:'Fresh Sip',cat:'FRESH',desc:'Choose a fresh fruit juice.',active:true}],loyaltyCards=JSON.parse(localStorage.getItem('co_loyalty_cards')||'null')||[{id:1,name:'Chill Out Rewards',description:'Earn points and unlock a cafe reward.',points_required:100,reward:'₹50 reward',active:true}],cart=JSON.parse(localStorage.getItem('co_cart')||'[]'),filter='All',role=null,user=null;const qr=new URLSearchParams(location.search).get('table')||'';
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2800)}function save(){localStorage.setItem('co_settings',JSON.stringify(settings));localStorage.setItem('co_menu',JSON.stringify(menu));localStorage.setItem('co_offers',JSON.stringify(offers));localStorage.setItem('co_loyalty_cards',JSON.stringify(loyaltyCards));localStorage.setItem('co_phone_numbers',JSON.stringify(phoneNumbers));localStorage.setItem('co_cart',JSON.stringify(cart))}function show(id){$(id).showModal()}function hide(id){if($(id).open)$(id).close()}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));$('year').textContent=new Date().getFullYear();
function normalizeSettings(){
  settings=settings||{};
  if(!Array.isArray(settings.phones)){
    const raw=String(settings.phone||'').trim();
    settings.phones=raw? [{label:'Call to Order',number:raw.replace(/^[^0-9+]*@\s*/,'').trim()||raw,active:true}] : [];
  }
  if(typeof settings.qrOrderingEnabled!=='boolean') settings.qrOrderingEnabled = settings.qrEnabled !== false;
  if(!settings.review) settings.review='https://share.google/RRQAxP3qKVVN0pDLg';
  if(!settings.instagram) settings.instagram='https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5';
}
function phoneBookText(){return settings.phones.filter(x=>x&&x.number).map(x=>`${x.label||'Call to Order'}: ${x.number}`).join(' | ')}
function phoneMeta(){return '__CO_PHONEBOOK__'+JSON.stringify(settings.phones)}
function reviewMeta(){return '__CO_META__'+JSON.stringify({review:settings.review||'',qrEnabled:settings.qrOrderingEnabled!==false})}
function parseDbSettings(row){
  let phones=[], phone=String(row.phone||'');
  if(phone.startsWith('__CO_PHONEBOOK__')){try{phones=JSON.parse(phone.slice('__CO_PHONEBOOK__'.length))}catch{phones=[]}}
  if(!phones.length && phone) phones=[{label:'Call to Order',number:phone.replace(/^[^0-9+]*@\s*/,'').trim()||phone,active:true}];
  let review=row.google_review_url||'', qrEnabled=true;
  if(review.startsWith('__CO_META__')){try{const m=JSON.parse(review.slice('__CO_META__'.length));review=m.review||'';qrEnabled=m.qrEnabled!==false}catch{}}
  return {name:row.cafe_name||'Chill Out',phone:phones.map(x=>`${x.label||'Call to Order'}: ${x.number||''}`).join(' | '),phones,review:review||'https://share.google/RRQAxP3qKVVN0pDLg',qrOrderingEnabled:qrEnabled,logo:row.logo_url||'',instagram:row.instagram_url||'https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5'};
}
function pub(){
  normalizeSettings();
  $('phone').innerHTML=settings.phones.filter(x=>x.active&&x.number).map(x=>`<a class="callBtn" href="tel:${esc(String(x.number).replace(/[^0-9+]/g,''))}">☎ ${esc(x.label||'Call to Order')}: ${esc(x.number)}</a>`).join('')||'<span>No phone ordering number set.</span>';
  $('cafeName').firstChild.textContent=(settings.name||'Chill Out').toUpperCase();
  $('reviewLink').href=settings.review||'#';if($('instagramLink'))$('instagramLink').href=settings.instagram||'https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5';
  if(settings.logo)$('logo').src=settings.logo;
  $('table').value=qr||$('table').value||'';
  $('tableHint').textContent=qr?'QR table detected: '+qr:'';
  const orderNote=$('orderingState');
  if(orderNote) orderNote.textContent=settings.qrOrderingEnabled?'🟢 Online / QR ordering is available.':'🔴 Online ordering is currently unavailable. Please order at the counter.';
  let cats=['All',...new Set(menu.filter(x=>x.active).map(x=>x.cat))];
  $('filters').innerHTML=cats.map(c=>`<button class="filter ${c==filter?'active':''}" data-c="${esc(c)}">${esc(c)}</button>`).join('');
  document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{filter=b.dataset.c;pub()});
  let ms=menu.filter(x=>x.active&&(filter==='All'||x.cat===filter));
  $('menuGrid').innerHTML=ms.map(x=>{const op=Number(x.original_price??x.originalPrice??x.price??0),sp=Number(x.offer_price??x.offerPrice??x.price??0);const hasOffer=op>sp;const priceText=(op<=0&&sp<=0)?'Price to be updated':(hasOffer?`<del>${money(op)}</del> <b>${money(sp)}</b>`:money(sp));return `<article class="card">${x.image_url?`<img class="menuPhoto" src="${esc(x.image_url)}" alt="${esc(x.name)}" loading="lazy">`:`<div class="icon">${x.icon||'🍽️'}</div>`}<h3>${esc(x.name)}</h3><p>${esc(x.desc||'')}</p><div class="cardBottom"><span class="price">${priceText}</span><button class="add" data-add="${x.id}" ${settings.qrOrderingEnabled?'':'disabled'}>${settings.qrOrderingEnabled?'Add':'Ordering off'}</button></div></article>`}).join('');
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));
  $('offerGrid').innerHTML=offers.filter(x=>x.active).map(x=>`<article class="offer"><span>${esc(x.cat||'SPECIAL')}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p><small>Offer available now</small></article>`).join('')||'<p>No current offers.</p>';
  renderCart();
}

function add(id){if(settings.qrOrderingEnabled===false)return toast('Online ordering is currently unavailable. Please order at the counter.');let m=menu.find(x=>x.id===id),q=cart.find(x=>x.id===id);q?q.qty++:cart.push({id,name:m.name,price:+m.price,qty:1});save();renderCart();toast(m.name+' added')};function change(id,d){let q=cart.find(x=>x.id===id);if(!q)return;q.qty+=d;if(q.qty<1)cart=cart.filter(x=>x.id!==id);save();renderCart()};function renderCart(){ $('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartLine"><span><b>${esc(x.name)}</b><br><small>${money(x.price)}</small></span><div class="qty"><button data-d="${x.id}">−</button>${x.qty}<button data-i="${x.id}">+</button></div><b>${money(x.price*x.qty)}</b></div>`).join(''):'<p>No items yet.</p>';document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>change(+b.dataset.d,-1));document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>change(+b.dataset.i,1));$('total').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0))}
$('cartBtn').onclick=$('heroCart').onclick=()=>{renderCart();show('cartModal')};$('customerBtn').onclick=()=>show('customerModal');$('skip').onclick=()=>{hide('customerModal');toast('Guest mode enabled')};$('staffBtn').onclick=()=>show('staffModal');
async function login(email,pw){if(demo){if(!email||!pw)throw Error('Enter demo email and password');return{id:'demo',email,role:email.toLowerCase().startsWith('owner')?'owner':'worker'}}let r=await db.auth.signInWithPassword({email,password:pw});if(r.error)throw r.error;let p=await db.from('profiles').select('role,full_name').eq('id',r.data.user.id).single();if(p.error)throw p.error;return{...r.data.user,role:p.data.role,name:p.data.full_name}}
function rememberEmail(key,inputId,rememberId){const saved=localStorage.getItem(key)||'';if(saved)$(inputId).value=saved;if($(rememberId))$(rememberId).checked=!!saved;$(inputId).addEventListener('input',()=>{if($(rememberId)?.checked)localStorage.setItem(key,$(inputId).value.trim())});$(rememberId)?.addEventListener('change',()=>{if($(rememberId).checked)localStorage.setItem(key,$(inputId).value.trim());else localStorage.removeItem(key)})}
rememberEmail('co_staff_email','staffEmail','staffRemember');rememberEmail('co_customer_email','custEmail','custRemember');
$('staffForm').onsubmit=async e=>{e.preventDefault();try{const em=$('staffEmail').value.trim().toLowerCase();if($('staffRemember').checked)localStorage.setItem('co_staff_email',em);else localStorage.removeItem('co_staff_email');user=await login(em,$('staffPass').value);role=user.role;hide('staffModal');role==='owner'?owner():role==='worker'?worker():toast('Staff role required')}catch(x){toast(x.message)}};
$('staffReset').onclick=async()=>{const em=$('staffEmail').value.trim();if(!em)return toast('Enter your work email first');if(demo)return toast('Password reset is unavailable in demo mode');try{const r=await db.auth.resetPasswordForEmail(em,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;toast('Password reset email sent')}catch(x){toast(x.message)}};
$('customerForm').onsubmit=async e=>{e.preventDefault();let email=$('custEmail').value.trim().toLowerCase(),pw=$('custPass').value,name=$('custName').value.trim(),phone=$('custPhone').value.trim();if(!email||!pw)return toast('Enter email/password or continue as Guest');try{if($('custRemember').checked)localStorage.setItem('co_customer_email',email);else localStorage.removeItem('co_customer_email');if(demo){user={id:'demo-customer',email,role:'customer',name,phone}}else{let r=await db.auth.signInWithPassword({email,password:pw});if(r.error){let sr=await db.auth.signUp({email,password:pw,options:{data:{full_name:name,phone}}});if(sr.error)throw r.error;r=sr;if(!r.data.user)throw Error('Account created. Please confirm your email, then sign in.')}if(r.error)throw r.error;user={id:r.data.user.id,email,role:'customer',name,phone};let pr=await db.from('profiles').upsert({id:user.id,role:'customer',full_name:name||null,phone:phone||null},{onConflict:'id'});if(pr.error)throw pr.error}hide('customerModal');toast('Customer account ready')}catch(x){toast(x.message)}};
async function place(){if(settings.qrOrderingEnabled===false)return toast('Online ordering is currently unavailable. Please order at the counter.');if(!cart.length)return toast('Cart is empty');let items=cart.map(x=>`${x.name} x${x.qty}`).join(', '),total=cart.reduce((a,x)=>a+x.price*x.qty,0),label=$('orderName').value.trim()||'Guest',table=$('table').value.trim(),note=$('note').value.trim(),row={customer_label:label+(table?' • Table '+table:''),items:items+(note?' • Note: '+note:''),total,status:'noted',created_at:new Date().toISOString(),customer_user_id:user?.role==='customer'?user.id:null};try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]');a.push({id:Date.now(),...row});localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').insert(row);if(r.error)throw r.error}cart=[];save();renderCart();hide('cartModal');toast('Order sent to cafe — '+money(total))}catch(x){toast(x.message)}}$('place').onclick=place;
async function staffCheck(wanted){if(demo)return true;let s=await db.auth.getUser();if(!s.data.user)throw Error('Please sign in');let p=await db.from('profiles').select('role').eq('id',s.data.user.id).single();if(p.error||p.data.role!==wanted)throw Error('Access denied')}
function tabs(){document.querySelectorAll('#ownerTabs button').forEach(b=>b.onclick=()=>loadOwnerTab(b.dataset.tab))}async function owner(){try{await staffCheck('owner');show('ownerModal');tabs();loadOwnerTab('overview')}catch(x){toast(x.message)}}async function loadOwnerTab(t){document.querySelectorAll('#ownerTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));let c=$('ownerContent');if(t==='overview')return overview(c);if(t==='menu')return menuAdmin(c);if(t==='offers')return offersAdmin(c);if(t==='orders')return ordersAdmin(c);if(t==='sales')return salesAdmin(c);if(t==='loyaltyAdmin')return loyaltyAdmin(c);if(t==='loyaltyCardsAdmin')return loyaltyCardsAdmin(c);if(t==='settings')return settingsAdmin(c);if(t==='phones')return phoneAdmin(c);if(t==='staff')return staffAdmin(c);if(t==='customers')return customersAdmin(c)}
async function getOrders(){if(demo)return JSON.parse(localStorage.getItem('co_orders')||'[]').sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));let r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(300);if(r.error)throw r.error;return r.data||[]}function orderRow(o){return `<div class="orderRow"><span><b>${esc(o.customer_label)}</b><br><small>${esc(o.items)}</small><br><small>${new Date(o.created_at).toLocaleString()}</small></span><span>${money(o.total)}<br><select data-status="${o.id}"><option ${o.status==='noted'?'selected':''}>noted</option><option ${o.status==='preparing'?'selected':''}>preparing</option><option ${o.status==='ready'?'selected':''}>ready</option><option ${o.status==='served'?'selected':''}>served</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select></span></div>`}async function bindStatuses(c,refresh){c.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]'),o=a.find(x=>String(x.id)===s.dataset.status);if(o)o.status=s.value;localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').update({status:s.value}).eq('id',s.dataset.status);if(r.error)throw r.error}toast('Status updated');refresh()}catch(x){toast(x.message)}})}
async function overview(c){let o=await getOrders(),d=o.filter(x=>x.created_at.slice(0,10)===today()&&x.status!=='cancelled'),rev=d.reduce((a,x)=>a+Number(x.total),0),open=o.filter(x=>['noted','preparing','ready'].includes(x.status)).length;c.innerHTML=`<div class="kpis"><div class="kpi"><span>ORDERS TODAY</span><b>${d.length}</b></div><div class="kpi"><span>REVENUE TODAY</span><b>${money(rev)}</b></div><div class="kpi"><span>OPEN ORDERS</span><b>${open}</b></div><div class="kpi"><span>MENU ITEMS</span><b>${menu.length}</b></div><div class="kpi"><span>MODE</span><b>${demo?'DEMO':'LIVE'}</b></div></div><div class="panel"><h3>Recent orders</h3>${d.slice(0,8).map(orderRow).join('')||'No orders today.'}</div>`}
async function menuAdmin(c){
  if(!demo){
    const r=await db.from('menu_items').select('*').order('category').order('name');
    if(r.error)return toast(r.error.message);
    menu=(r.data||[]).map(x=>({id:x.id,name:x.name,cat:x.category,desc:x.description,price:x.offer_price??x.price,original_price:x.original_price??x.price,offer_price:x.offer_price??x.price,image_url:x.image_url||'',active:x.is_available!==false,icon:x.icon||'🍽️'}));
  }
  c.innerHTML=`<div class="panel"><div class="row"><div><h3>Menu Management</h3><p class="tiny">Owner has full control: add, edit, enable/disable, delete, change name, category, description, photo, original price and selling/offer price.</p></div><button class="solid" id="newMenu">Add Item</button></div><div>${menu.map(x=>`<div class="adminRow"><span><b>${esc(x.name)}</b><br><small>${esc(x.cat)} · ${money(x.original_price??x.price)} → ${money(x.offer_price??x.price)} · ${x.active?'Available':'Disabled'}</small></span><span class="actions"><button class="small" data-togglem="${x.id}">${x.active?'Disable':'Enable'}</button><button class="small" data-editm="${x.id}">Edit</button><button class="small danger" data-delm="${x.id}">Delete</button></span></div>`).join('')}</div></div>`;
  $('newMenu').onclick=()=>edit('menu');
  c.querySelectorAll('[data-editm]').forEach(b=>b.onclick=()=>edit('menu',+b.dataset.editm));
  c.querySelectorAll('[data-togglem]').forEach(b=>b.onclick=()=>toggleMenu(+b.dataset.togglem));
  c.querySelectorAll('[data-delm]').forEach(b=>b.onclick=()=>del('menu',+b.dataset.delm));
}
async function toggleMenu(id){
  const x=menu.find(v=>v.id===id); if(!x)return;
  const next=!x.active;
  try{
    if(demo){x.active=next;save();pub();loadOwnerTab('menu');return}
    const r=await db.from('menu_items').update({is_available:next}).eq('id',id);
    if(r.error)throw r.error;
    x.active=next; pub(); await menuAdmin($('ownerContent')); toast(next?'Menu item enabled':'Menu item disabled');
  }catch(e){toast(e.message)}
}
function offersAdmin(c){c.innerHTML=`<div class="panel"><div class="row"><h3>Offers Management</h3><button class="solid" id="newOffer">Add Offer</button></div>${offers.map(x=>`<div class="adminRow"><span><b>${esc(x.title)}</b><br><small>${esc(x.cat)} · ${x.active?'Active':'Hidden'}</small></span><span class="actions"><button class="small" data-edito="${x.id}">Edit</button><button class="small danger" data-delo="${x.id}">Delete</button></span></div>`).join('')}</div>`;$('newOffer').onclick=()=>edit('offer');c.querySelectorAll('[data-edito]').forEach(b=>b.onclick=()=>edit('offer',+b.dataset.edito));c.querySelectorAll('[data-delo]').forEach(b=>b.onclick=()=>del('offer',+b.dataset.delo))}async function ordersAdmin(c){let o=await getOrders();c.innerHTML=`<div class="panel"><div class="row"><h3>All Orders</h3><button class="outline" id="ro">Refresh</button></div><div id="olist">${o.map(orderRow).join('')||'No orders.'}</div></div>`;await bindStatuses($('olist'),()=>ordersAdmin(c));$('ro').onclick=()=>ordersAdmin(c)}
async function salesAdmin(c){let o=await getOrders();let from=today(),to=today();c.innerHTML=`<div class="panel"><h3>Sales Report</h3><input id="from" type="date" value="${from}"><input id="to" type="date" value="${to}"><button class="solid" id="runSales">Run Report</button><div id="report"></div></div>`;$('runSales').onclick=async()=>{let f=$('from').value,t=$('to').value,r=(await getOrders()).filter(x=>x.created_at.slice(0,10)>=f&&x.created_at.slice(0,10)<=t&&x.status!=='cancelled'),v=r.reduce((a,x)=>a+Number(x.total),0);$('report').innerHTML=`<div class="reportCards"><div class="reportCard"><span>ORDERS</span><b>${r.length}</b></div><div class="reportCard"><span>REVENUE</span><b>${money(v)}</b></div><div class="reportCard"><span>AVG ORDER</span><b>${money(r.length?v/r.length:0)}</b></div><div class="reportCard"><span>PERIOD</span><b>${f} → ${t}</b></div></div><table><tr><th>Date</th><th>Items</th><th>Total</th></tr>${r.map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString()}</td><td>${esc(x.items)}</td><td>${money(x.total)}</td></tr>`).join('')}</table>`};$('runSales').click()}
function loyaltyAdmin(c){let l=JSON.parse(localStorage.getItem('co_loyalty')||'{"per100":10,"rewardPoints":100,"rewardValue":50}');c.innerHTML=`<div class="panel"><h3>Loyalty Rules</h3><label>Points per ₹100<input id="lp" type="number" value="${l.per100}"></label><label>Reward points<input id="lrp" type="number" value="${l.rewardPoints}"></label><label>Reward value ₹<input id="lrv" type="number" value="${l.rewardValue}"></label><button class="solid" id="saveL">Save</button></div>`;$('saveL').onclick=async()=>{l={per100:+$('lp').value,rewardPoints:+$('lrp').value,rewardValue:+$('lrv').value};localStorage.setItem('co_loyalty',JSON.stringify(l));if(!demo){let r=await db.from('loyalty_settings').upsert({id:1,points_per_100:l.per100,reward_points:l.rewardPoints,reward_value:l.rewardValue});if(r.error)return toast(r.error.message)}toast('Loyalty rules saved')}}function loyaltyCardsAdmin(c){
  c.innerHTML=`<div class="panel"><div class="row"><div><h3>Loyalty Cards</h3><p class="tiny">Create multiple loyalty cards with different names, point targets and rewards. Active cards are shown publicly to customers.</p></div><button class="solid" id="newLoyaltyCard">Add Card</button></div>${loyaltyCards.map(x=>`<div class="adminRow"><span><b>${esc(x.name)}</b><br><small>${esc(x.points_required)} points · ${esc(x.reward)} · ${x.active?'Visible':'Hidden'}</small></span><span class="actions"><button class="small" data-editlc="${x.id}">Edit</button><button class="small danger" data-dellc="${x.id}">Delete</button></span></div>`).join('')||'<p>No loyalty cards yet.</p>'}</div>`;
  $('newLoyaltyCard').onclick=()=>editLoyaltyCard();
  c.querySelectorAll('[data-editlc]').forEach(b=>b.onclick=()=>editLoyaltyCard(+b.dataset.editlc));
  c.querySelectorAll('[data-dellc]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this loyalty card?'))return;let id=+b.dataset.dellc;if(demo){loyaltyCards=loyaltyCards.filter(x=>x.id!==id);save();pub();loadOwnerTab('loyaltyCardsAdmin');return}let r=await db.from('loyalty_cards').delete().eq('id',id);if(r.error)return toast(r.error.message);loyaltyCards=loyaltyCards.filter(x=>x.id!==id);pub();loadOwnerTab('loyaltyCardsAdmin')});
}
function editLoyaltyCard(id){const x=loyaltyCards.find(v=>v.id===id);$('lcId').value=id||'';$('loyaltyCardTitle').textContent=id?'Edit Loyalty Card':'Add Loyalty Card';$('lcName').value=x?.name||'';$('lcDesc').value=x?.description||'';$('lcPoints').value=x?.points_required??100;$('lcReward').value=x?.reward||'';$('lcActive').checked=x?.active??true;show('loyaltyCardModal')}
function settingsAdmin(c){
  normalizeSettings();
  const rows=settings.phones.map((p,i)=>`<div class="adminRow phoneRow"><span><b>${esc(p.label||'Call to Order')}</b><br><small>${esc(p.number||'')} · ${p.active?'Active':'Disabled'}</small></span><span class="actions"><button class="small" data-phone-edit="${i}">Edit</button><button class="small danger" data-phone-del="${i}">Delete</button></span></div>`).join('');
  c.innerHTML=`<div class="panel"><h3>Public Settings</h3><input id="sn" value="${esc(settings.name)}" placeholder="Cafe name"><input id="sr" value="${esc(settings.review)}" placeholder="Google review URL"><input id="sl" value="${esc(settings.logo)}" placeholder="Logo URL (optional)"><input id="si" value="${esc(settings.instagram||'https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5')}" placeholder="Instagram URL">
  <label class="toggle"><input id="qrEnabled" type="checkbox" ${settings.qrOrderingEnabled?'checked':''}> <b>QR / Online Ordering ON</b></label>
  <p class="security">When OFF, customers can still see the menu and phone numbers, but cannot place QR/online orders.</p>
  <h3>Call to Order Numbers</h3><div id="phoneList">${rows||'<p>No numbers yet.</p>'}</div><button class="outline" id="addPhone">+ Add Phone Number</button>
  <div class="ownerBox"><b>Primary Owner</b><br>${esc('Editorgaadu@gmail.com')}<p>Primary Owner cannot be removed. Additional owners use the same Owner Dashboard permissions; account promotion is controlled through Supabase Auth/RLS.</p></div>
  <button class="solid" id="saveS">Save Settings</button><p class="security"><b>Security:</b> only the owner role may update settings in production.</p></div>`;
  function editPhone(i){const p=settings.phones[i]||{label:'Call to Order',number:'',active:true};const label=prompt('Phone label',p.label||'Call to Order');if(label===null)return;const number=prompt('Phone number',p.number||'');if(number===null)return;const active=confirm('Keep this number active?');settings.phones[i]={label:label.trim()||'Call to Order',number:number.trim(),active};renderRows();}
  function renderRows(){const box=$('phoneList');box.innerHTML=settings.phones.map((p,i)=>`<div class="adminRow phoneRow"><span><b>${esc(p.label||'Call to Order')}</b><br><small>${esc(p.number||'')} · ${p.active?'Active':'Disabled'}</small></span><span class="actions"><button class="small" data-phone-edit="${i}">Edit</button><button class="small danger" data-phone-del="${i}">Delete</button></span></div>`).join('')||'<p>No numbers yet.</p>';box.querySelectorAll('[data-phone-edit]').forEach(b=>b.onclick=()=>editPhone(+b.dataset.phoneEdit));box.querySelectorAll('[data-phone-del]').forEach(b=>b.onclick=()=>{settings.phones.splice(+b.dataset.phoneDel,1);renderRows()});}
  renderRows();$('addPhone').onclick=()=>{settings.phones.push({label:'Call to Order',number:'',active:true});editPhone(settings.phones.length-1)};
  $('saveS').onclick=async()=>{let n={...settings,name:$('sn').value.trim()||'Chill Out',review:$('sr').value.trim()||'https://share.google/RRQAxP3qKVVN0pDLg',logo:$('sl').value.trim(),instagram:$('si').value.trim()||'https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5',qrOrderingEnabled:$('qrEnabled').checked};settings=n;if(demo){save()}else{let r=await db.from('site_settings').upsert({id:1,cafe_name:n.name,phone:phoneMeta(),google_review_url:reviewMeta(),logo_url:n.logo,instagram_url:n.instagram,qr_ordering_enabled:n.qrOrderingEnabled});if(r.error)return toast(r.error.message);save()}pub();toast('Settings saved')};
}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file||!file.type.startsWith('image/'))return reject(Error('Please choose an image file'));const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};img.onerror=()=>reject(Error('Could not read image'));img.src=r.result};r.onerror=()=>reject(Error('Could not read image file'));r.readAsDataURL(file)})}
function edit(type,id){let o=type==='menu'?menu.find(x=>x.id===id):offers.find(x=>x.id===id);$('editId').value=id||'';$('editType').value=type;$('editTitle').textContent=(id?'Edit ':'Add ')+(type==='menu'?'Menu Item':'Offer');$('editName').value=o?.name||o?.title||'';$('editCat').value=o?.cat||'';$('editDesc').value=o?.desc||'';$('editPrice').value=o?.price??'';$('editOriginalPrice').value=o?.original_price??o?.originalPrice??o?.price??'';$('editOfferPrice').value=o?.offer_price??o?.offerPrice??o?.price??'';$('editPhotoUrl').value=o?.image_url||'';$('editPhoto').value='';const isMenu=type==='menu';$('editPrice').style.display='none';$('menuPricing').style.display=isMenu?'block':'none';$('menuPhotoField').style.display=isMenu?'block':'none';$('editActive').checked=o?.active??true;show('editModal')}async function del(type,id){if(!confirm('Delete this item?'))return;if(demo){if(type==='menu')menu=menu.filter(x=>x.id!==id);else offers=offers.filter(x=>x.id!==id);save();pub();loadOwnerTab(type==='menu'?'menu':'offers');return}let table=type==='menu'?'menu_items':'offers',r=await db.from(table).delete().eq('id',id);if(r.error)return toast(r.error.message);loadOwnerTab(type==='menu'?'menu':'offers')}
$('loyaltyCardForm').onsubmit=async e=>{e.preventDefault();let id=+$('lcId').value||null;let item={name:$('lcName').value.trim(),description:$('lcDesc').value.trim(),points_required:+$('lcPoints').value,reward:$('lcReward').value.trim(),active:$('lcActive').checked};if(!item.name||!item.reward||item.points_required<1)return toast('Enter card name, points and reward');try{if(demo){if(id){let x=loyaltyCards.find(v=>v.id===id);if(x)Object.assign(x,{...item,id})}else loyaltyCards.push({id:Date.now(),...item});save()}else{let p={name:item.name,description:item.description,points_required:item.points_required,reward:item.reward,is_active:item.active};let r=id?await db.from('loyalty_cards').update(p).eq('id',id):await db.from('loyalty_cards').insert(p).select().single();if(r.error)throw r.error;if(id){let x=loyaltyCards.find(v=>v.id===id);if(x)Object.assign(x,item)}else if(r.data)loyaltyCards.push({id:r.data.id,...item})}hide('loyaltyCardModal');pub();toast('Loyalty card saved');loadOwnerTab('loyaltyCardsAdmin')}catch(x){toast(x.message)}};
$('editForm').onsubmit=async e=>{e.preventDefault();let type=$('editType').value,id=+$('editId').value||null;try{if(type==='menu'){let original=Number($('editOriginalPrice').value||0),offer=Number($('editOfferPrice').value||0);if(original<0||offer<0)return toast('Prices cannot be negative');if(offer>original&&original>0)return toast('Offer price should not be higher than original price');let photo=$('editPhotoUrl').value.trim();const file=$('editPhoto').files?.[0];if(file){photo=await compressImage(file)}let item={name:$('editName').value.trim(),category:$('editCat').value.trim()||'Other',description:$('editDesc').value.trim(),original_price:original,offer_price:offer||original,price:offer||original,image_url:photo||null,is_available:$('editActive').checked};if(!item.name||original<0)return toast('Enter item name and a valid original price');if(demo){let o={id:id||Date.now(),name:item.name,cat:item.category,desc:item.description,original_price:item.original_price,offer_price:item.offer_price,price:item.price,image_url:item.image_url,active:item.is_available,icon:'🍽️'};if(id)Object.assign(menu.find(x=>x.id===id),o);else menu.push(o);save()}else{let r=id?await db.from('menu_items').update(item).eq('id',id):await db.from('menu_items').insert(item);if(r.error)throw r.error}}else{let item={title:$('editName').value.trim(),category:$('editCat').value.trim()||'SPECIAL',description:$('editDesc').value.trim(),is_active:$('editActive').checked};if(!item.title)return toast('Enter offer title');if(demo){let o={id:id||Date.now(),title:item.title,cat:item.category,desc:item.description,active:item.is_active};if(id)Object.assign(offers.find(x=>x.id===id),o);else offers.push(o);save()}else{let r=id?await db.from('offers').update(item).eq('id',id):await db.from('offers').insert(item);if(r.error)throw r.error}}hide('editModal');pub();toast('Saved');loadOwnerTab(type==='menu'?'menu':'offers')}catch(x){toast(x.message)}};;
async function phoneAdmin(c){
  c.innerHTML=`<div class="panel"><h3>Phone Orders</h3><p>Customer-facing phone numbers are managed in Settings.</p>${phoneNumbers.map(p=>`<div class="adminRow"><span><b>${esc(p.label||'Call to Order')}</b><br><small>${esc(p.phone||'')} · ${p.enabled?'Enabled':'Disabled'}</small></span><a class="small" href="tel:${esc(String(p.phone||'').replace(/[^0-9+]/g,''))}">Call</a></div>`).join('')||'<p>No phone numbers configured.</p>'}</div>`;
}
async function staffAdmin(c){
  if(demo){c.innerHTML='<div class="panel"><h3>Owners & Workers</h3><p>Staff management is available in Live mode.</p></div>';return}
  let r=await db.functions.invoke('manage-staff-v2',{body:{action:'list'}});if(r.error)throw r.error;let staff=r.data?.staff||[],primary=r.data?.primary_owner_email||'Editorgaadu@gmail.com';
  c.innerHTML=`<div class="panel"><h3>Owners & Workers</h3><p class="tiny">Primary Owner: <b>${esc(primary)}</b></p><div class="staffAdd"><input id="staffAddEmail" type="email" placeholder="Email"><select id="staffAddRole"><option value="worker">Worker</option><option value="owner">Owner</option></select><button class="solid" id="staffAddBtn">Add / Invite</button></div><div id="staffList">${staff.map(x=>`<div class="adminRow"><span><b>${esc(x.full_name||x.id)}</b><br><small>${esc(x.role)} · ${esc(x.email||'')}</small></span><button class="small danger" data-remove-staff="${esc(x.email||'')}">Remove</button></div>`).join('')||'<p>No additional staff yet.</p>'}</div></div>`;
  $('staffAddBtn').onclick=async()=>{let email=$('staffAddEmail').value.trim().toLowerCase(),rr=$('staffAddRole').value;if(!email)return toast('Enter an email');const b=$('staffAddBtn');b.disabled=true;b.textContent='Sending…';try{let x=await db.functions.invoke('manage-staff-v2',{body:{action:'invite',email,role:rr}});if(x.error){let msg=x.data?.error||x.error?.message||'Could not add staff';throw Error(msg)}toast(x.data?.message||'Invitation sent');await staffAdmin(c)}catch(e){toast(e.message||'Could not add staff')}finally{b.disabled=false;b.textContent='Add / Invite'}};
  c.querySelectorAll('[data-remove-staff]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove access for this user?'))return;try{let x=await db.functions.invoke('manage-staff-v2',{body:{action:'remove',email:b.dataset.removeStaff}});if(x.error)throw x.error;toast('Access removed');staffAdmin(c)}catch(e){toast(e.message)}});
}
async function customersAdmin(c){
  if(demo){c.innerHTML='<div class="panel"><h3>Customer Details</h3><p>Customer details appear here in Live mode.</p></div>';return}
  let cr=await db.functions.invoke('manage-staff-v2',{body:{action:'list-customers'}});if(cr.error)throw cr.error;let customers=cr.data?.customers||[];let orders=await getOrders();let map={};orders.forEach(o=>{if(o.customer_user_id){let m=map[o.customer_user_id]||{count:0,total:0,last:o.created_at};m.count++;m.total+=Number(o.total||0);if(new Date(o.created_at)>new Date(m.last))m.last=o.created_at;map[o.customer_user_id]=m}});
  c.innerHTML=`<div class="panel"><div class="row"><div><h3>Customer Details</h3><p class="tiny">Registered customer information. Guest orders are shown in Orders but are not linked to a customer account.</p></div><button class="outline" id="refreshCustomers">Refresh</button></div><div class="customerTable">${customers.map(x=>{let m=map[x.id]||{count:0,total:0,last:null};return `<div class="customerCard"><div><b>${esc(x.full_name||'Customer')}</b><br><small>${esc(x.email||'No email')}</small><br><small>Phone: ${esc(x.phone||'Not provided')}</small></div><div><b>${m.count} orders</b><br><small>Spent ${money(m.total)}</small><br><small>Joined ${x.created_at?new Date(x.created_at).toLocaleDateString():'—'}</small></div></div>`}).join('')||'<p>No registered customers yet.</p>'}</div></div>`;$('refreshCustomers').onclick=()=>customersAdmin(c);
}
async function worker(){try{await staffCheck('worker');show('workerModal');loadWorker()}catch(x){toast(x.message)}}async function loadWorker(){let o=await getOrders();$('workerOrders').innerHTML=o.map(orderRow).join('')||'No orders.';await bindStatuses($('workerOrders'),loadWorker)}$('workerForm').onsubmit=async e=>{e.preventDefault();let row={customer_label:$('wCustomer').value,items:$('wItems').value,total:+$('wTotal').value,status:'noted',created_at:new Date().toISOString()};try{if(demo){let a=JSON.parse(localStorage.getItem('co_orders')||'[]');a.push({id:Date.now(),...row});localStorage.setItem('co_orders',JSON.stringify(a))}else{let r=await db.from('orders').insert({...row,created_by:user.id});if(r.error)throw r.error}e.target.reset();toast('Order saved');loadWorker()}catch(x){toast(x.message)}};$('refreshWorker').onclick=loadWorker;
$('ownerLogout').onclick=async()=>{if(db)await db.auth.signOut();hide('ownerModal');role=null};$('workerLogout').onclick=async()=>{if(db)await db.auth.signOut();hide('workerModal');role=null};pub();if(!demo)(async()=>{try{let s=await db.from('site_settings').select('*').eq('id',1).maybeSingle();if(s.data)settings={name:s.data.cafe_name,phone:s.data.phone,review:s.data.google_review_url,logo:s.data.logo_url,instagram:s.data.instagram_url||'https://www.instagram.com/chill0ut_gannavram?stkn=cWtwdDl1azV5ZDR5',qrOrderingEnabled:s.data.qr_ordering_enabled!==false};let pn=await db.from('phone_numbers').select('*').eq('enabled',true).order('id');if(pn.data)phoneNumbers=pn.data;let m=await db.from('menu_items').select('*').eq('is_available',true).order('name');if(m.data)menu=m.data.map(x=>({id:x.id,name:x.name,cat:x.category,desc:x.description,price:x.offer_price??x.price,original_price:x.original_price??x.price,offer_price:x.offer_price??x.price,image_url:x.image_url||'',active:true,icon:x.icon||'🍽️'}));let o=await db.from('offers').select('*').eq('is_active',true);if(o.data)offers=o.data.map(x=>({id:x.id,title:x.title,cat:x.category,desc:x.description,active:true}));let lc=await db.from('loyalty_cards').select('*').order('created_at');if(lc.data)loyaltyCards=lc.data.map(x=>({id:x.id,name:x.name,description:x.description,points_required:x.points_required,reward:x.reward,active:x.is_active}));pub()}catch(e){console.warn(e)}})()})();
