-- Chill Out Cafe V2: run in Supabase SQL Editor.
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null default 'customer' check(role in ('owner','worker','customer')),full_name text,created_at timestamptz default now());
create table if not exists public.site_settings(id bigint primary key check(id=1),cafe_name text not null default 'Chill Out',phone text not null default 'Sagar @ 9886025749',google_review_url text not null default 'https://share.google/RRQAxP3qKVVN0pDLg',logo_url text not null default '',qr_ordering_enabled boolean not null default true,primary_owner_email text not null default 'Editorgaadu@gmail.com',updated_at timestamptz default now());insert into public.site_settings(id) values(1) on conflict(id) do nothing;
create table if not exists public.menu_items(id bigint generated always as identity primary key,name text not null,category text not null default 'Other',description text,price numeric(10,2) not null check(price>=0),image_url text,icon text,is_available boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.offers(id bigint generated always as identity primary key,title text not null,category text default 'SPECIAL',description text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.loyalty_settings(id bigint primary key check(id=1),points_per_100 integer default 10 check(points_per_100>=0),reward_points integer default 100 check(reward_points>0),reward_value numeric(10,2) default 50 check(reward_value>=0),updated_at timestamptz default now());insert into public.loyalty_settings(id) values(1) on conflict(id) do nothing;insert into public.phone_numbers(label,phone,enabled) select 'Sagar','9886025749',true where not exists(select 1 from public.phone_numbers);
create table if not exists public.loyalty_accounts(user_id uuid primary key references auth.users(id) on delete cascade,points integer default 0 check(points>=0),updated_at timestamptz default now());
create table if not exists public.loyalty_transactions(id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete cascade,points_delta integer not null,reason text not null,order_id bigint,created_at timestamptz default now());
create table if not exists public.phone_numbers(id bigint generated always as identity primary key,label text not null,phone text not null,enabled boolean not null default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.orders(id bigint generated always as identity primary key,customer_user_id uuid references auth.users(id) on delete set null,customer_label text not null,items text not null,total numeric(10,2) not null check(total>=0),status text default 'noted' check(status in ('noted','preparing','ready','served','cancelled')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz default now());
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create or replace function public.is_role(wanted text) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role=wanted);$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,role) values(new.id,'customer') on conflict(id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security;alter table public.site_settings enable row level security;alter table public.menu_items enable row level security;alter table public.offers enable row level security;alter table public.loyalty_settings enable row level security;alter table public.loyalty_accounts enable row level security;alter table public.loyalty_transactions enable row level security;alter table public.orders enable row level security;alter table public.phone_numbers enable row level security;
create policy "public read menu" on public.menu_items for select using(true);create policy "owner menu" on public.menu_items for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "public read offers" on public.offers for select using(true);create policy "owner offers" on public.offers for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "public read settings" on public.site_settings for select using(true);create policy "owner settings" on public.site_settings for update using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "public read phone numbers" on public.phone_numbers for select using(enabled=true or public.is_role('owner'));create policy "owner manage phone numbers" on public.phone_numbers for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "public read loyalty settings" on public.loyalty_settings for select using(true);create policy "owner loyalty settings" on public.loyalty_settings for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "own profile" on public.profiles for select using(auth.uid()=id or public.is_role('owner'));create policy "owner profiles" on public.profiles for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "own loyalty" on public.loyalty_accounts for select using(auth.uid()=user_id or public.is_role('owner'));create policy "owner loyalty" on public.loyalty_accounts for all using(public.is_role('owner')) with check(public.is_role('owner'));
create policy "own transactions" on public.loyalty_transactions for select using(auth.uid()=user_id or public.is_role('owner'));create policy "owner transactions" on public.loyalty_transactions for all using(public.is_role('owner')) with check(public.is_role('owner'));
-- Guest QR ordering is intentionally allowed; staff dashboards are protected.
create policy "guest can place orders" on public.orders for insert with check(status='noted' and total>=0 and length(customer_label)<=60 and length(items)<=1000);
create policy "staff read orders" on public.orders for select using(public.is_role('owner') or public.is_role('worker'));
create policy "staff update orders" on public.orders for update using(public.is_role('owner') or public.is_role('worker')) with check(public.is_role('owner') or public.is_role('worker'));
create policy "owner delete orders" on public.orders for delete using(public.is_role('owner'));
-- After creating Auth accounts, promote them with their UUID:
-- update public.profiles set role='owner',full_name='Cafe Owner' where id='OWNER_UUID';
-- update public.profiles set role='worker',full_name='Worker Name' where id='WORKER_UUID';
-- Never expose a Supabase service_role/secret key in the frontend.

-- The current app stores the owner-managed phone book in site_settings.phone and QR state + review URL in site_settings.google_review_url using private metadata prefixes. This keeps the existing schema compatible. A future clean migration may split these into dedicated columns/tables.
