-- Chill Out Cafe V9 menu migration
-- Seeds the menu from the uploaded FROUNT PG.pdf. Owner can edit every field later.
-- Existing starter/demo items are removed by name, then the PDF menu is added.

delete from public.menu_items where name in (
  'Classic Waffle','Chocolate Thick Shake','Fresh Fruit Juice','Ice Cream Scoop','Tea / Coffee','Cafe Snacks'
);

insert into public.menu_items (name, category, description, price, original_price, offer_price, is_available, icon)
values
('Watermelon','Natural Juice','Fresh watermelon juice',59,59,59,true,'🍉'),
('Grape','Natural Juice','Fresh grape juice',69,69,69,true,'🍇'),
('Pineapple','Natural Juice','Fresh pineapple juice',69,69,69,true,'🍍'),
('Orange','Natural Juice','Fresh orange juice',69,69,69,true,'🍊'),
('Carrot','Natural Juice','Fresh carrot juice',79,79,79,true,'🥕'),
('Beetroot','Natural Juice','Fresh beetroot juice',79,79,79,true,'🥤'),
('Apple beetroot carrot (ABC)','Natural Juice','Apple, beetroot and carrot juice',89,89,89,true,'🍎'),
('Chocolate Shake','Milk Shake','Rich chocolate milk shake',109,109,109,true,'🥤'),
('Vanilla Shake','Milk Shake','Classic vanilla milk shake',99,99,99,true,'🥤'),
('Strawberry Shake','Milk Shake','Strawberry milk shake',109,109,109,true,'🍓'),
('Butter Scotch Shake','Milk Shake','Butterscotch milk shake',119,119,119,true,'🥤'),
('Black Current Shake','Milk Shake','Black current milk shake',139,139,139,true,'🥤'),
('Oreo Shake','Milk Shake','Oreo milk shake',99,99,99,true,'🍪'),
('KitKat Shake','Milk Shake','KitKat milk shake',119,119,119,true,'🍫'),
('Nutella Shake','Milk Shake','Nutella milk shake',139,139,139,true,'🍫'),
('Snickers Shake','Milk Shake','Snickers milk shake',119,119,119,true,'🥜'),
('Green Pista Shake','Milk Shake','Green pista milk shake',119,119,119,true,'🥤'),
('Kesar Badam Shake','Milk Shake','Kesar badam milk shake',139,139,139,true,'🥛'),
('Belgium Dark Chocolate Shake','Milk Shake','Belgian dark chocolate milk shake',149,149,149,true,'🍫'),
('Banana Fruit Milkshake','Fruit Milkshakes','Banana fruit milkshake',69,69,69,true,'🍌'),
('Pineapple Fruit Milkshake','Fruit Milkshakes','Pineapple fruit milkshake',79,79,79,true,'🍍'),
('Apple Fruit Milkshake','Fruit Milkshakes','Apple fruit milkshake',89,89,89,true,'🍎'),
('Grape Fruit Milkshake','Fruit Milkshakes','Grape fruit milkshake',79,79,79,true,'🍇'),
('Muskmelon Fruit Milkshake','Fruit Milkshakes','Muskmelon fruit milkshake',79,79,79,true,'🍈'),
('Sapota Fruit Milkshake','Fruit Milkshakes','Sapota fruit milkshake',79,79,79,true,'🥤'),
('Papaya Fruit Milkshake','Fruit Milkshakes','Papaya fruit milkshake',69,69,69,true,'🍊'),
('Pomegranate Fruit Milkshake','Fruit Milkshakes','Pomegranate fruit milkshake',89,89,89,true,'🥤'),
('Strawberry Fruit Milkshake','Fruit Milkshakes','Strawberry fruit milkshake',99,99,99,true,'🍓'),
('Avocado Fruit Milkshake','Fruit Milkshakes','Avocado fruit milkshake',179,179,179,true,'🥑'),
('Mango Fruit Milkshake','Fruit Milkshakes','Mango fruit milkshake',89,89,89,true,'🥭'),
('Strawberry Smoothie','Smoothies','Fresh strawberry smoothie',199,199,199,true,'🍓'),
('Mango Smoothie','Smoothies','Fresh mango smoothie',179,179,179,true,'🥭'),
('Banana Smoothie','Smoothies','Fresh banana smoothie',179,179,179,true,'🍌'),
('Mixed Berry Smoothie','Smoothies','Mixed berry smoothie',229,229,229,true,'🫐'),
('Chocolate Banana Smoothie','Smoothies','Chocolate banana smoothie',219,219,219,true,'🍫'),
('Peanut Butter Banana Smoothie','Smoothies','Peanut butter banana smoothie',229,229,229,true,'🥜'),
('Blue Berry Smoothie','Smoothies','Blueberry smoothie',229,229,229,true,'🫐'),
('Avocado Smoothie','Smoothies','Avocado smoothie',249,249,249,true,'🥑'),
('Dry Fruit Smoothie','Smoothies','Dry fruit smoothie',269,269,269,true,'🥜'),
('Oreo Smoothie','Smoothies','Oreo smoothie',219,219,219,true,'🍪'),
('Protein Power Smoothie','Smoothies','Protein power smoothie',279,279,279,true,'💪'),
('Chocolate Delight','Thick Shakes','Chocolate thick shake',179,179,179,true,'🥤'),
('Belgium Chocolate','Thick Shakes','Belgian chocolate thick shake',199,199,199,true,'🍫'),
('Nutella Brownie','Thick Shakes','Nutella brownie thick shake',199,199,199,true,'🍫'),
('Nutella Chocolate','Thick Shakes','Nutella chocolate thick shake',199,199,199,true,'🍫'),
('Caramel Carnival','Thick Shakes','Caramel thick shake',199,199,199,true,'🥤'),
('Triple Choco Chip','Thick Shakes','Triple chocolate chip thick shake',199,199,199,true,'🍫'),
('KitKat Thick Shake','Thick Shakes','KitKat thick shake',199,199,199,true,'🍫'),
('Oreo Nutella','Thick Shakes','Oreo Nutella thick shake',209,209,209,true,'🍪'),
('Caramel Butterscotch','Thick Shakes','Caramel butterscotch thick shake',249,249,249,true,'🥤'),
('Hazelnut Cookie','Thick Shakes','Hazelnut cookie thick shake',249,249,249,true,'🍪'),
('Dry Fruit Thick Shake','Thick Shakes','Dry fruit thick shake',269,269,269,true,'🥜'),
('American Dry Fruit','Thick Shakes','American dry fruit thick shake',269,269,269,true,'🥜'),
('Ferrero Rocher','Thick Shakes','Ferrero Rocher thick shake',269,269,269,true,'🍫'),
('Lemon Mojito','Mocktails','Fresh lemon mojito',99,99,99,true,'🍋'),
('Virgin Mojito','Mocktails','Refreshing virgin mojito',109,109,109,true,'🍹'),
('Strawberry Mojito','Mocktails','Strawberry mojito',109,109,109,true,'🍓'),
('Blue Lagon','Mocktails','Blue lagoon mocktail',129,129,129,true,'🧋'),
('Green Apple Mojito','Mocktails','Green apple mojito',119,119,119,true,'🍏'),
('Black Current Mojito','Mocktails','Black current mojito',129,129,129,true,'🍹'),
('Pineapple Mojito','Mocktails','Pineapple mojito',129,129,129,true,'🍍'),
('Orange Mojito','Mocktails','Orange mojito',139,139,139,true,'🍊'),
('Kiwi Mojito','Mocktails','Kiwi mojito',139,139,139,true,'🥝'),
('Blueberry Mojito','Mocktails','Blueberry mojito',149,149,149,true,'🫐'),
('Mint Cooler','Mocktails','Mint cooler',129,129,129,true,'🌿'),
('Veg Classic Burger','Burgers','Classic veg burger',99,99,99,true,'🍔'),
('Veg Cheese Burger','Burgers','Veg cheese burger',119,119,119,true,'🍔'),
('Aloo Tikki Burger','Burgers','Aloo tikki burger',109,109,109,true,'🍔'),
('Paneer Burger','Burgers','Paneer burger',149,149,149,true,'🍔'),
('Paneer Cheese Burger','Burgers','Paneer cheese burger',169,169,169,true,'🍔'),
('Crispy Veg Burger','Burgers','Crispy veg burger',129,129,129,true,'🍔'),
('Crispy Veg Cheese Burger','Burgers','Crispy veg cheese burger',149,149,149,true,'🍔'),
('Spicy Mexican Veg Burger','Burgers','Spicy Mexican veg burger',159,159,159,true,'🍔'),
('Double Patty Veg Burger','Burgers','Double patty veg burger',179,179,179,true,'🍔'),
('Double Patty Cheese Burger','Burgers','Double patty cheese burger',199,199,199,true,'🍔'),
('Classic Chicken Burger','Burgers','Classic chicken burger',119,119,119,true,'🍔'),
('Chicken Cheese Burger','Burgers','Chicken cheese burger',139,139,139,true,'🍔'),
('Chicken Double Patty Burger','Burgers','Chicken double patty burger',169,169,169,true,'🍔'),
('Spicy Chicken Burger','Burgers','Spicy chicken burger',149,149,149,true,'🍔'),
('Peri-Peri Chicken Burger','Burgers','Peri-peri chicken burger',159,159,159,true,'🍔'),
('Chicken Cheese Burger Special','Burgers','Chicken cheese burger special',179,179,179,true,'🍔'),
('Chicken Crispy Burger','Burgers','Chicken crispy burger',169,169,169,true,'🍔'),
('Chicken Mayo Burger','Burgers','Chicken mayo burger',139,139,139,true,'🍔'),
('Chicken Sausage Burger','Burgers','Chicken sausage burger',139,139,139,true,'🍔'),
('Plain Veg Sandwich','Sandwiches','Plain veg sandwich',79,79,79,true,'🥪'),
('Veg Cheese Sandwich','Sandwiches','Veg cheese sandwich',99,99,99,true,'🥪'),
('Corn and Cheese Sandwich','Sandwiches','Corn and cheese sandwich',109,109,109,true,'🥪'),
('Paneer Sandwich','Sandwiches','Paneer sandwich',119,119,119,true,'🥪'),
('Peri Peri Veg Sandwich','Sandwiches','Peri peri veg sandwich',119,119,119,true,'🥪'),
('Egg Sandwich','Sandwiches','Egg sandwich',119,119,119,true,'🥪'),
('Chicken Sandwich','Sandwiches','Chicken sandwich',129,129,129,true,'🥪'),
('Cheese Chicken Sandwich','Sandwiches','Cheese chicken sandwich',159,159,159,true,'🥪'),
('Choco Heaven','Sundaes','Chocolate brownie fudge, vanilla and strawberry ice cream with gems, chocolate, caramel nuts, choco chips, cornflakes, cashew nuts and chocolate strawberry sauce.',199,199,199,true,'🍨'),
('Chocolate Child','Sundaes','Chocolate brownie, Swiss cake, crunchy caramel ice cream, KitKat, Snickers, cashew nuts, choco chips and chocolate peach sauce.',219,219,219,true,'🍨'),
('Chocolate Chunky','Sundaes','Nutty delight, crunchy caramel, Scottish crunch ice cream, KitKat, gems, cream wafer and nuts with variety sauce.',219,219,219,true,'🍨'),
('Hot Chocolate Fudge','Sundaes','Chocolate and vanilla ice cream with hot chocolate sauce, caramel, cashew nuts, choco chips and corn flakes.',219,219,219,true,'🍨'),
('Chocolate Brownie Sizzling','Sundaes','Sizzling chocolate brownie, vanilla ice cream, chocolate chips, cashew nuts and hot dark chocolate sauce.',229,229,229,true,'🍨'),
('Gun Bot','Sundaes','Vanilla and chocolate ice cream, cashew nuts, caramel nuts, corn flakes, kissmiss and chocolate sauce.',169,169,169,true,'🍨'),
('Choco Craze','Sundaes','Chocolate, vanilla and butterscotch ice cream with corn flakes, cashew, kissmiss and caramel nuts.',199,199,199,true,'🍨'),
('Caramel Spender','Sundaes','Chocolate chips, Spanish delight, vanilla and chocolate ice cream, caramel nuts and cashew with peach sauce.',219,219,219,true,'🍨'),
('American Coconut','Sundaes','Chocolate Spanish, vanilla slice, cashew nuts, chocos, caramel nuts and chocolate sauce.',219,219,219,true,'🍨'),
('Full House Chocolate','Sundaes','Chocolate brownie, Scottish crunch, chocolate ice cream, gems, biscuit, KitKat, caramel nuts, chocolate chips and cream wafer.',239,239,239,true,'🍨'),
('Chocolate Snickers','Sundaes','Vanilla, butterscotch and chocolate brownie ice cream with gems, Snickers, caramel nuts and chocolate-buttercotch sauce.',219,219,219,true,'🍨'),
('Double Lock','Sundaes','Strawberry, butterscotch and blackcurrent ice creams with cashew nuts, badam and butterscotch sauce.',169,169,169,true,'🍨'),
('Fiery Folic','Sundaes','Butterscotch and kesar pista ice creams, dry fruits, chocos, butterscotch and pista sauce.',169,169,169,true,'🍨'),
('Black Station','Sundaes','Black current and kesar pista ice cream, nuts, black kissmiss and chocolate sauces.',179,179,179,true,'🍨'),
('Snow Rock','Sundaes','Fig and honey, strawberry, mango and kesar pista ice creams, dry fruits and sauces.',299,299,299,true,'🍨'),
('Wet Dream','Sundaes','Crunchy caramel and nutty delight ice creams, cashew and caramel nuts, badam butterscotch and peach sauce.',169,169,169,true,'🍨'),
('Royal Salama','Sundaes','Strawberry, butterscotch and blackcurrent ice creams, cashew nuts, badam and butterscotch sauce.',149,149,149,true,'🍨'),
('Choco Lava','Sundaes','Chocolate brownie, nutty delight, crunchy caramel, brownie cake, cashew nut, caramel nut and dark chocolate sauce.',199,199,199,true,'🍨'),
('Kids Jone','Sundaes','Vanilla and strawberry ice cream, wafer and cherry.',120,120,120,true,'🍨'),
('Lucina Girl','Sundaes','Vanilla and chocolate ice cream, wafer and cherry.',130,130,130,true,'🍨'),
('Jungle Fun','Sundaes','Swiss cake, butterscotch ice creams, cone, gems, cream wafer, chocolate shots and variety sauces.',150,150,150,true,'🍨'),
('Chocolate Mork','Sundaes','Chocolate brownie, crunchy caramel, ice creams, KitKat, Bounty and gems with variety sauces.',150,150,150,true,'🍨'),
('Normal Fries','Fries','Classic salted fries',89,89,89,true,'🍟'),
('Piri Piri Fries','Fries','Piri piri fries',109,109,109,true,'🍟'),
('Chilli Garlic Fries','Fries','Chilli garlic fries',119,119,119,true,'🍟'),
('Chicken Loaded Fries','Fries','Chicken loaded fries',250,250,250,true,'🍟'),
('Potato Wedges','Fries','Crispy potato wedges',99,99,99,true,'🥔'),
('Fish Fries','Fries','Fish fries',219,219,219,true,'🐟'),
('Chicken Popcorn','Snacks','Chicken popcorn',199,199,199,true,'🍗'),
('Chicken Nuggets 6pc','Snacks','Six piece chicken nuggets',160,160,160,true,'🍗'),
('Chicken Strips 6pc','Snacks','Six piece chicken strips',180,180,180,true,'🍗'),
('Chicken Strips 4pc','Snacks','Four piece chicken strips',299,299,299,true,'🍗'),
('5pc Wings','Snacks','Five piece chicken wings',300,300,300,true,'🍗'),
('Piri Piri Wings','Snacks','Piri piri chicken wings',320,320,320,true,'🍗'),
('Mexican Cheese Balls','Snacks','Mexican cheese balls',139,139,139,true,'🧀'),
('Veg Fingers','Snacks','Crispy veg fingers',159,159,159,true,'🍟'),
('Chicken Samosa 4pc','Snacks','Four piece chicken samosa',139,139,139,true,'🥟'),
('Veg Spring Rolls 6pc','Snacks','Six piece veg spring rolls',189,189,189,true,'🥟'),
('Veg Momos 6pc','Momos','Six piece veg momos',149,149,149,true,'🥟'),
('Paneer Momos 6pc','Momos','Six piece paneer momos',159,159,159,true,'🥟'),
('Chicken Momos 6pc','Momos','Six piece chicken momos',159,159,159,true,'🥟'),
('Chicken Tikka Momos 6pc','Momos','Six piece chicken tikka momos',169,169,169,true,'🥟'),
('Veg White Sauce Pasta','Pasta','Veg white sauce pasta',249,249,249,true,'🍝'),
('Veg Red Sauce Pasta','Pasta','Veg red sauce pasta',249,249,249,true,'🍝'),
('Chicken White Sauce Pasta','Pasta','Chicken white sauce pasta',279,279,279,true,'🍝'),
('Chicken Red Sauce Pasta','Pasta','Chicken red sauce pasta',279,279,279,true,'🍝'),
('Belgian Chocolate Sushi','Chill Out Special','Belgian chocolate sushi',169,169,169,true,'🍫'),
('Triple Chocolate Sushi','Chill Out Special','Triple chocolate sushi',179,179,179,true,'🍫'),
('Dark and Milk Chocolate Sushi','Chill Out Special','Dark and milk chocolate sushi',169,169,169,true,'🍫'),
('KitKat Sushi','Chill Out Special','KitKat sushi',189,189,189,true,'🍫'),
('Oreo Sushi','Chill Out Special','Oreo sushi',189,189,189,true,'🍪'),
('Nutella Sushi','Chill Out Special','Nutella sushi',189,189,189,true,'🍫'),
('Dry Fruit Loaded Sushi','Chill Out Special','Dry fruit loaded sushi',229,229,229,true,'🥜'),
('Belgian Chocolate Pancake','Mini Pancakes','Belgian chocolate pancake',99,99,99,true,'🥞'),
('Triple Chocolate Pancake','Mini Pancakes','Triple chocolate pancake',109,109,109,true,'🥞'),
('Dark and Milk Fantasy Pancake','Mini Pancakes','Dark and milk fantasy pancake',99,99,99,true,'🥞'),
('Oreo Fantasy Pancake','Mini Pancakes','Oreo fantasy pancake',109,109,109,true,'🥞'),
('KitKat Pancake','Mini Pancakes','KitKat pancake',109,109,109,true,'🥞'),
('Nutella Pancake','Mini Pancakes','Nutella pancake',119,119,119,true,'🥞'),
('Dark Fantasy Pancake','Mini Pancakes','Dark fantasy pancake',109,109,109,true,'🥞'),
('Extra Chocochips','Add-ons','Extra chocolate chips',40,40,40,true,'🍫'),
('Extra Sprinkles','Add-ons','Extra sprinkles',30,30,30,true,'✨'),
('Banana','Chocolates','Banana chocolate treat',149,149,149,true,'🍌'),
('Pineapple','Chocolates','Pineapple chocolate treat',159,159,159,true,'🍍'),
('Mixed Fruits Platter + Brownie','Chocolates','Mixed fruits platter with brownie',199,199,199,true,'🍓'),
('Strawberry Chocolate','Chocolates','Strawberry chocolate treat',159,159,159,true,'🍓'),
('Blueberry Chocolate','Chocolates','Blueberry chocolate treat',159,159,159,true,'🫐'),
('Brownie Chocolate','Chocolates','Brownie chocolate treat',169,169,169,true,'🍫'),
('Hot Chocolate','Melt-in-Moments','Hot chocolate',219,219,219,true,'☕'),
('Belgian Chocolate Brownie','Melt-in-Moments','Belgian chocolate brownie',229,229,229,true,'🍫'),
('Triple Chocolate Brownie','Melt-in-Moments','Triple chocolate brownie',199,199,199,true,'🍫'),
('Dark Fantasy Brownie','Melt-in-Moments','Dark fantasy brownie',209,209,209,true,'🍫'),
('Oreo Brownie','Melt-in-Moments','Oreo brownie',199,199,199,true,'🍪'),
('Dry Fruit Loaded Brownie','Melt-in-Moments','Dry fruit loaded brownie',199,199,199,true,'🥜'),
('Bubble Waffle With Triple Chocolate','Bubble Waffles','Bubble waffle with triple chocolate',199,199,199,true,'🧇'),
('Bubble Waffle With Ice Cream','Bubble Waffles','Bubble waffle with ice cream',199,199,199,true,'🧇'),
('Bubble Waffle With Fruit','Bubble Waffles','Bubble waffle with fruit',199,199,199,true,'🧇'),
('Oreo Bubble Waffle','Bubble Waffles','Oreo bubble waffle',199,199,199,true,'🧇'),
('KitKat Bubble Waffle','Bubble Waffles','KitKat bubble waffle',209,209,209,true,'🧇'),
('Nutella Bubble Waffle','Bubble Waffles','Nutella bubble waffle',199,199,199,true,'🧇'),
('Belgian Chocolate Bubble Waffle','Bubble Waffles','Belgian chocolate bubble waffle',199,199,199,true,'🧇'),
('Dark and Milk Bubble Waffle','Bubble Waffles','Dark and milk bubble waffle',199,199,199,true,'🧇'),
('Dark Fantasy Bubble Waffle','Bubble Waffles','Dark fantasy bubble waffle',209,209,209,true,'🧇'),
('Lotus Biscoff Bubble Waffle','Bubble Waffles','Lotus Biscoff bubble waffle',259,259,259,true,'🧇'),
('Waffle With Triple Chocolate','Waffles','Waffle with triple chocolate',89,89,89,true,'🧇'),
('Waffle With Ice Cream','Waffles','Waffle with ice cream',109,109,109,true,'🧇'),
('Waffle With Fruit','Waffles','Waffle with fruit',109,109,109,true,'🧇'),
('Oreo Waffle','Waffles','Oreo waffle',99,99,99,true,'🧇'),
('KitKat Waffle','Waffles','KitKat waffle',99,99,99,true,'🧇'),
('Nutella Waffle','Waffles','Nutella waffle',109,109,109,true,'🧇'),
('Belgian Chocolate Waffle','Waffles','Belgian chocolate waffle',99,99,99,true,'🧇'),
('Dark and Milk Waffle','Waffles','Dark and milk waffle',99,99,99,true,'🧇'),
('Dark Fantasy Waffle','Waffles','Dark fantasy waffle',109,109,109,true,'🧇'),
('Extra Ice Cream','Waffle Add-ons','Extra ice cream',50,50,50,true,'🍦'),
('Extra Sprinkles / Toppings','Waffle Add-ons','Extra sprinkles or toppings',40,40,40,true,'✨'),
('Extra Chocochips','Waffle Add-ons','Extra chocolate chips',40,40,40,true,'🍫'),
('Extra Fruits','Waffle Add-ons','Extra fruits',80,80,80,true,'🍓'),
('Extra Dry Fruits','Waffle Add-ons','Extra dry fruits',110,110,110,true,'🥜'),
('Extra Gems','Waffle Add-ons','Extra gems',20,20,20,true,'🍬'),
('Extra Marshmallows','Waffle Add-ons','Extra marshmallows',20,20,20,true,'☁️'),
('Ferrero Rocher Add-on','Waffle Add-ons','Ferrero Rocher add-on',49,49,49,true,'🍫'),
('Green Tea','Tea','Green tea',49,49,49,true,'🍵'),
('Lemon and Honey Tea','Tea','Lemon and honey tea',49,49,49,true,'🍋');
